branch-defaults:
  master:
    environment: biosys-staging
  staging:
    environment: biosys-staging
  uat:
    environment: biosys-uat
  oeh_uat:
    environment: biosys-uat
  production:
    environment: biosys-production
  oeh_production:
    environment: biosys-production
  slug_uat:
    environment: biosys-uat
  slug_prod:
    environment: biosys-production
global:
  application_name: biosys
  branch: master
  default_ec2_keyname: aws-eb
  default_platform: Python 3.6
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
